name: CD - API

on:
  push:
    paths:
      - 'api/CHANGELOG.md'
  workflow_dispatch:

env:
  NODE_VERSION: '16'

jobs:
  check:
    name: 'Check Deployable'
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    outputs:
      changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
      type: ${{ steps.check.outputs.type }}
      is_manual: ${{ steps.manual.outputs.is_manual }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify Manual Deploy
        id: manual
        run: echo ::set-output name=is_manual::${{ github.event_name == 'workflow_dispatch' }}

      - name: Version Check
        id: check
        if: steps.manual.outputs.is_manual == 'false'
        uses: EndBug/version-check@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-name: ./api/package.json

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: [check]

    if: needs.check.outputs.changed == 'true' || needs.check.outputs.is_manual == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'master'
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_SSH_HOST }}/${{ secrets.DOKKU_APPNAME }}'
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
