name: CD - API

on:
  push:
    paths:
      - 'api/CHANGELOG.md'

env:
  NODE_VERSION: '16'

jobs:
  check-version:
    name: 'Check Deployable'
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    outputs:
      changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
      type: ${{ steps.check.outputs.type }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Version Check
        id: check
        uses: EndBug/version-check@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-name: ./api/package.json

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: [check-version]

    if: needs.check-version.outputs.changed == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'master'
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_SSH_HOST }}/${{ secrets.DOKKU_APPNAME }}'
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
