name: CI - Client

on:
  push:
    paths:
      - 'client/**'
      - 'package.json'

env:
  NODE_VERSION: '16'

jobs:
  cache-modules:
    name: Cache Node Modules
    runs-on: ubuntu-latest

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Check for dupe action
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1

      - name: Cache Node Modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ env.NODE_VERSION }}-${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci --no-optional

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [cache-modules]

    if: ${{ needs.cache-modules.outputs.should_skip != 'true' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Retrieve Node Modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ env.NODE_VERSION }}-${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build --workspace client

      - name: Validate
        run: npm run validate --workspace client

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [cache-modules]

    if: ${{ needs.cache-modules.outputs.should_skip != 'true' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Retrieve Node Modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ env.NODE_VERSION }}-${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}

      - name: Lint
        run: npm run lint --workspace client
